// react/src/pages/CourseDetail.tsx
import { useState, useEffect, useMemo, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuestionSearch } from '../hooks/useQuestionSearch';
import { useTags } from '../hooks/useTags';
import { useCompletion } from '../context/CompletionContext';
import { useFavorites } from '../context/FavoritesContext';
import { useAuth } from '../context/AuthContext';
import { Tag } from '../types';
import { ArrowLeft, Heart, ChevronDown, ChevronRight, Check, ExternalLink } from 'lucide-react';
import './CourseDetail.css';

interface CourseUrl {
  url: string;
  tooltip: string;
  color: string;
  visibleString?: string;
}

interface CourseQuestion {
  filename: string;
  title: string;
  urls?: CourseUrl[];
  tags?: Tag[];
}

interface CourseSection {
  title: string;
  description?: string;
  questions: CourseQuestion[];
  unitKey: string;
}

interface Course {
  course_name: string;
  course_description: string;
  [key: string]: unknown;
}

export function CourseDetail() {
  const { filename } = useParams<{ filename: string }>();
  const navigate = useNavigate();
  const { allQuestions, isLoaded: questionsLoaded } = useQuestionSearch();
  const { getDifficultyTag, getTags } = useTags();
  const { isCompleted } = useCompletion();
  const { isFavorite, toggleFavorite } = useFavorites();
  const { isAuthenticated } = useAuth();

  const [course, setCourse] = useState<Course | null>(null);
  const [courseSections, setCourseSections] = useState<CourseSection[]>([]);
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(true);

  // Extract sections from course data
  const extractSections = useCallback((courseData: Course) => {
    const sections: CourseSection[] = [];

    const formatTitle = (key: string) => {
      return key
        .replace(/_/g, ' ')
        .split(' ')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
    };

    const formatQuestionTitle = (filename: string) => {
      return filename
        .split('-')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
    };

    const enrichQuestion = (question: { filename: string; urls?: CourseUrl[] }): CourseQuestion => {
      const questionData = allQuestions.find(q => q.filename === question.filename);
      const tags: Tag[] = [];

      if (questionData) {
        tags.push(getDifficultyTag(questionData.difficulty));
        if (questionData.tags.length > 0) {
          tags.push(...getTags(questionData.tags));
        }
      }

      return {
        filename: question.filename,
        title: formatQuestionTitle(question.filename),
        urls: question.urls,
        tags
      };
    };

    for (const [key, value] of Object.entries(courseData)) {
      if (key !== 'course_name' && key !== 'course_description' && key !== 'duration' &&
          key !== 'difficulty' && key !== 'filename' && key !== 'keywords' && key !== 'badge') {
        if (typeof value === 'object' && value !== null) {
          // This is a container for sections (units, weeks, etc.)
          for (const [sectionKey, sectionValue] of Object.entries(value as Record<string, unknown>)) {
            if (typeof sectionValue === 'object' && sectionValue !== null) {
              const section = sectionValue as { title?: string; description?: string; questions?: unknown[] };
              const sectionData: CourseSection = {
                title: section.title || formatTitle(sectionKey),
                description: section.description,
                questions: [],
                unitKey: sectionKey
              };

              if (section.questions && Array.isArray(section.questions)) {
                for (const q of section.questions) {
                  if (typeof q === 'string') {
                    sectionData.questions.push(enrichQuestion({ filename: q }));
                  } else if (typeof q === 'object' && q !== null && 'filename' in q) {
                    sectionData.questions.push(enrichQuestion(q as { filename: string; urls?: CourseUrl[] }));
                  }
                }
              }

              sections.push(sectionData);
            }
          }
        }
      }
    }

    return sections;
  }, [allQuestions, getDifficultyTag, getTags]);

  // Load course
  useEffect(() => {
    if (!filename || !questionsLoaded) return;

    setLoading(true);
    fetch(`/courses/${filename}.json`)
      .then(res => {
        if (!res.ok) throw new Error('Not found');
        return res.json();
      })
      .then((data: Course) => {
        setCourse(data);
        const sections = extractSections(data);
        setCourseSections(sections);
        // Expand first section by default
        if (sections.length > 0) {
          setExpandedSections(new Set([sections[0].unitKey]));
        }
        setLoading(false);
      })
      .catch(() => {
        navigate('/courses');
      });
  }, [filename, questionsLoaded, extractSections, navigate]);

  const toggleSection = useCallback((unitKey: string) => {
    setExpandedSections(prev => {
      const next = new Set(prev);
      if (next.has(unitKey)) {
        next.delete(unitKey);
      } else {
        next.add(unitKey);
      }
      return next;
    });
  }, []);

  const handleQuestionClick = useCallback((questionFilename: string) => {
    window.open(`/questions/${questionFilename}`, '_blank');
  }, []);

  const handleUrlClick = useCallback((e: React.MouseEvent, url: string) => {
    e.stopPropagation();
    window.open(url, '_blank');
  }, []);

  const handleToggleFavorite = useCallback(async () => {
    if (!isAuthenticated) {
      navigate('/auth/sign-in');
      return;
    }
    if (filename) {
      await toggleFavorite(filename);
    }
  }, [isAuthenticated, navigate, filename, toggleFavorite]);

  // Progress calculations
  const totalQuestions = useMemo(() => {
    return courseSections.reduce((sum, section) => sum + section.questions.length, 0);
  }, [courseSections]);

  const completedCount = useMemo(() => {
    let count = 0;
    courseSections.forEach(section => {
      section.questions.forEach(q => {
        if (isCompleted(q.filename)) count++;
      });
    });
    return count;
  }, [courseSections, isCompleted]);

  const overallProgress = totalQuestions > 0 ? Math.round((completedCount / totalQuestions) * 100) : 0;

  const getSectionProgress = useCallback((section: CourseSection) => {
    const completed = section.questions.filter(q => isCompleted(q.filename)).length;
    return section.questions.length > 0 ? Math.round((completed / section.questions.length) * 100) : 0;
  }, [isCompleted]);

  const getSectionCompletedCount = useCallback((section: CourseSection) => {
    return section.questions.filter(q => isCompleted(q.filename)).length;
  }, [isCompleted]);

  if (loading || !course) {
    return (
      <div className="course-detail-page">
        <div className="loading">
          <div className="spinner" />
          <span>Loading course...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="course-detail-page">
      <div className="course-detail-header">
        <button className="back-btn" onClick={() => navigate('/courses')}>
          <ArrowLeft size={20} />
          <span>Back to Courses</span>
        </button>

        <div className="course-info">
          <div className="course-title-row">
            <h1>{course.course_name}</h1>
            <button
              className={`favorite-btn ${isFavorite(filename || '') ? 'active' : ''}`}
              onClick={handleToggleFavorite}
              aria-label={isFavorite(filename || '') ? 'Remove from favorites' : 'Add to favorites'}
            >
              <Heart size={20} fill={isFavorite(filename || '') ? 'currentColor' : 'none'} />
            </button>
          </div>
          <p className="course-description">{course.course_description}</p>

          <div className="course-progress">
            <div className="progress-text">
              <span>{completedCount} of {totalQuestions} problems completed</span>
              <span>{overallProgress}%</span>
            </div>
            <div className="progress-bar">
              <div className="progress-fill" style={{ width: `${overallProgress}%` }} />
            </div>
          </div>
        </div>
      </div>

      <div className="course-sections">
        {courseSections.map((section, index) => (
          <div key={section.unitKey} className="section">
            <button
              className="section-header"
              onClick={() => toggleSection(section.unitKey)}
            >
              <div className="section-toggle">
                {expandedSections.has(section.unitKey) ? (
                  <ChevronDown size={20} />
                ) : (
                  <ChevronRight size={20} />
                )}
              </div>
              <div className="section-info">
                <span className="section-number">{index + 1}</span>
                <div className="section-title-wrapper">
                  <h3>{section.title}</h3>
                  {section.description && (
                    <p className="section-description">{section.description}</p>
                  )}
                </div>
              </div>
              <div className="section-progress">
                <span className="progress-count">
                  {getSectionCompletedCount(section)}/{section.questions.length}
                </span>
                <div className="mini-progress-bar">
                  <div
                    className="mini-progress-fill"
                    style={{ width: `${getSectionProgress(section)}%` }}
                  />
                </div>
              </div>
            </button>

            {expandedSections.has(section.unitKey) && (
              <div className="section-content">
                <ul className="questions-list">
                  {section.questions.map((question) => (
                    <li key={question.filename}>
                      <button
                        className="question-item"
                        onClick={() => handleQuestionClick(question.filename)}
                      >
                        <div className="question-status">
                          {isCompleted(question.filename) ? (
                            <Check size={16} className="completed-icon" />
                          ) : (
                            <div className="uncompleted-circle" />
                          )}
                        </div>
                        <div className="question-content">
                          <span className="question-title">{question.title}</span>
                          {question.tags && question.tags.length > 0 && (
                            <div className="question-tags">
                              {question.tags.map((tag, i) => (
                                <span
                                  key={i}
                                  className="tag"
                                  style={{ backgroundColor: `${tag.color}20`, color: tag.color }}
                                >
                                  {tag.text}
                                </span>
                              ))}
                            </div>
                          )}
                        </div>
                        <div className="question-actions">
                          {question.urls && question.urls.map((url, i) => (
                            <button
                              key={i}
                              className="url-btn"
                              onClick={(e) => handleUrlClick(e, url.url)}
                              title={url.tooltip}
                              style={{ color: url.color }}
                            >
                              <ExternalLink size={14} />
                            </button>
                          ))}
                        </div>
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

// frontend/src/app/pages/course-detail/course-detail.component.ts
import { Component, OnInit, OnDestroy, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { LocalStorageService } from '../../services/local-storage.service';
import { CompletionService } from '../../services/completion.service';
import { FavoritesService } from '../../services/favorites.service';
import { AuthService } from '../../services/auth.service';
import { TagService } from '../../services/tag.service';
import { QuestionSearchService } from '../../services/question-search.service';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

interface CourseTag {
  text: string;
  color: string;
}

interface CourseUrl {
  url: string;
  tooltip: string;
  color: string;
  visibleString?: string;
}

interface CourseQuestion {
  filename: string;
  title: string;
  urls?: CourseUrl[];
  tags?: CourseTag[];
}

interface CourseSection {
  title: string;
  description?: string;
  questions: CourseQuestion[];
  unitKey: string;
}

interface Course {
  course_name: string;
  course_description: string;
  [key: string]: any;
}

@Component({
  selector: 'app-course-detail',
  imports: [CommonModule],
  templateUrl: './course-detail.component.html',
  styleUrl: './course-detail.component.scss'
})
export class CourseDetailComponent implements OnInit, OnDestroy {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private http = inject(HttpClient);
  private localStorageService = inject(LocalStorageService);
  private completionService = inject(CompletionService);
  private favoritesService = inject(FavoritesService);
  private authService = inject(AuthService);
  private tagService = inject(TagService);
  private questionSearchService = inject(QuestionSearchService);
  private destroy$ = new Subject<void>();

  course: Course | null = null;
  courseSections: CourseSection[] = [];
  courseName = '';
  private questionsIndexLoaded = false;
  expandedSections: Set<string> = new Set();

  ngOnInit() {
    // Wait for questions index to load first
    this.questionSearchService.isIndexLoaded().pipe(takeUntil(this.destroy$)).subscribe(loaded => {
      if (loaded && !this.questionsIndexLoaded) {
        this.questionsIndexLoaded = true;

        // Now load the course
        if (this.courseName) {
          this.loadCourse();
        }
      }
    });

    this.route.params.pipe(takeUntil(this.destroy$)).subscribe(params => {
      this.courseName = params['filename'];

      // Load course if questions index is already loaded
      if (this.questionsIndexLoaded) {
        this.loadCourse();
      }
    });

    // Load favorites and completions if authenticated
    if (this.authService.isAuthenticated()) {
      this.favoritesService.getFavorites().pipe(takeUntil(this.destroy$)).subscribe({
        error: () => {
          // Silently fail if not authenticated or error occurs
        }
      });

      this.completionService.getCompletions().pipe(takeUntil(this.destroy$)).subscribe({
        error: () => {
          // Silently fail if not authenticated or error occurs
        }
      });
    }
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private loadCourse() {
    this.http.get<Course>(`/courses/${this.courseName}.json`).subscribe({
      next: (data) => {
        this.course = data;
        this.extractSections();
      },
      error: (error) => {
        console.error('Failed to load course:', error);
        this.router.navigate(['/courses']);
      }
    });
  }

  private extractSections() {
    if (!this.course) return;
    
    const sections: CourseSection[] = [];
    
    // Iterate through all course properties to find sections
    for (const [key, value] of Object.entries(this.course)) {
      if (key !== 'course_name' && key !== 'course_description' && key !== 'duration' && key !== 'difficulty') {
        if (typeof value === 'object' && value !== null) {
          // This is likely a container for sections (like 'weeks', 'days', 'modules')
          this.extractSectionsFromContainer(value, sections);
        }
      }
    }
    
    this.courseSections = sections;

    // Expand first section by default
    if (sections.length > 0) {
      this.expandedSections.add(sections[0].unitKey);
    }
  }

  private extractSectionsFromContainer(container: any, sections: CourseSection[]) {
    for (const [key, value] of Object.entries(container)) {
      if (typeof value === 'object' && value !== null) {
        const section: CourseSection = {
          title: (value as any).title || this.formatSectionTitle(key),
          description: (value as any).description,
          questions: [],
          unitKey: key
        };
        
        // Extract questions from this section
        if ((value as any).questions && Array.isArray((value as any).questions)) {
          for (const question of (value as any).questions) {
            if (typeof question === 'string') {
              // Old format: just string filename
              section.questions.push(this.enrichQuestionData({
                filename: question,
                title: this.formatQuestionTitle(question)
              }));
            } else if (typeof question === 'object' && question.filename) {
              // New format: object with filename and optional attributes
              // Load tags from question file (via index) instead of using course tags
              section.questions.push(this.enrichQuestionData({
                filename: question.filename,
                title: this.formatQuestionTitle(question.filename),
                urls: question.urls
              }));
            }
          }
        }
        
        sections.push(section);
      }
    }
  }

  private formatSectionTitle(key: string): string {
    return key
      .replace(/_/g, ' ')
      .split(' ')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  private formatQuestionTitle(filename: string): string {
    return filename
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  /**
   * Enrich question data with tags from the question file (via index)
   */
  private enrichQuestionData(question: CourseQuestion): CourseQuestion {
    // Look up question in the index to get difficulty and tags
    const allQuestions = this.questionSearchService.getAllQuestions();
    const questionData = allQuestions.find(q => q.filename === question.filename);

    if (questionData) {
      // Convert difficulty and tags to CourseTag objects with colors
      const tags: CourseTag[] = [];

      // Add difficulty tag (always present)
      tags.push(this.tagService.getDifficultyTag(questionData.difficulty));

      // Add other tags if any
      if (questionData.tags.length > 0) {
        tags.push(...this.tagService.getTags(questionData.tags));
      }

      return {
        ...question,
        tags: tags
      };
    }

    return question;
  }

  onQuestionClick(question: CourseQuestion) {
    const url = this.router.serializeUrl(
      this.router.createUrlTree(['/questions', question.filename])
    );
    window.open(url, '_blank');
  }

  goBack() {
    this.router.navigate(['/courses']);
  }

  isFavorite(): boolean {
    return this.favoritesService.isFavorite(this.courseName);
  }

  toggleFavorite(): void {
    if (!this.authService.isAuthenticated()) {
      this.router.navigate(['/sign-in']);
      return;
    }

    if (this.isFavorite()) {
      this.favoritesService.removeFavorite(this.courseName).pipe(takeUntil(this.destroy$)).subscribe({
        error: (err) => {
          console.error('Error removing favorite:', err);
        }
      });
    } else {
      this.favoritesService.addFavorite(this.courseName).pipe(takeUntil(this.destroy$)).subscribe({
        error: (err) => {
          console.error('Error adding favorite:', err);
        }
      });
    }
  }

  isQuestionCompleted(questionFilename: string): boolean {
    if (this.authService.isAuthenticated()) {
      return this.completionService.isCompleted(questionFilename);
    } else {
      return this.localStorageService.isQuestionCompleted(questionFilename);
    }
  }

  onUrlClick(event: Event, url: string) {
    event.stopPropagation(); // Prevent the question click from firing
    window.open(url, '_blank');
  }

  onUnitClick(unitKey: string) {
    this.router.navigate(['/courses', this.courseName, unitKey]);
  }

  // Progress tracking methods
  toggleSection(unitKey: string): void {
    if (this.expandedSections.has(unitKey)) {
      this.expandedSections.delete(unitKey);
    } else {
      this.expandedSections.add(unitKey);
    }
  }

  isSectionExpanded(unitKey: string): boolean {
    return this.expandedSections.has(unitKey);
  }

  getOverallProgress(): number {
    const total = this.getTotalQuestions();
    const completed = this.getCompletedCount();
    return total > 0 ? Math.round((completed / total) * 100) : 0;
  }

  getTotalQuestions(): number {
    return this.courseSections.reduce((sum, section) => sum + section.questions.length, 0);
  }

  getCompletedCount(): number {
    let count = 0;
    this.courseSections.forEach(section => {
      section.questions.forEach(q => {
        if (this.isQuestionCompleted(q.filename)) count++;
      });
    });
    return count;
  }

  getSectionProgress(section: CourseSection): number {
    const completed = this.getSectionCompletedCount(section);
    return section.questions.length > 0 ? Math.round((completed / section.questions.length) * 100) : 0;
  }

  getSectionCompletedCount(section: CourseSection): number {
    return section.questions.filter(q => this.isQuestionCompleted(q.filename)).length;
  }

  getSectionNumber(section: CourseSection): number {
    return this.courseSections.indexOf(section) + 1;
  }
}
<div class="course-detail-container">
  <div class="course-header">
    <div class="header-top">
      <button class="back-btn" (click)="goBack()">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="19" y1="12" x2="5" y2="12"/>
          <polyline points="12 19 5 12 12 5"/>
        </svg>
        Back to Courses
      </button>
      <button
        class="favorite-btn"
        [class.favorited]="isFavorite()"
        (click)="toggleFavorite()"
        *ngIf="course"
        [attr.aria-label]="isFavorite() ? 'Remove from favorites' : 'Add to favorites'"
      >
        <svg width="24" height="24" viewBox="0 0 24 24" [attr.fill]="isFavorite() ? 'currentColor' : 'none'" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
        </svg>
      </button>
    </div>
    <h1 *ngIf="course">{{ course.course_name }}</h1>
    <p *ngIf="course" class="course-description">{{ course.course_description }}</p>

    <!-- Overall Progress -->
    <div class="overall-progress" *ngIf="course && getTotalQuestions() > 0">
      <div class="progress-header">
        <span class="progress-label">Overall Progress</span>
        <span class="progress-text">{{ getCompletedCount() }}/{{ getTotalQuestions() }} completed ({{ getOverallProgress() }}%)</span>
      </div>
      <div class="progress-bar-container">
        <div class="progress-bar-fill" [style.width.%]="getOverallProgress()"></div>
      </div>
    </div>
  </div>
  
  <div class="sections-container" *ngIf="courseSections.length > 0">
    <div *ngFor="let section of courseSections" class="course-section">
      <div class="section-header" (click)="toggleSection(section.unitKey)">
        <div class="section-title-row">
          <h2>
            <span class="section-number">{{ getSectionNumber(section) }}.</span>
            {{ section.title }}
            <span class="question-count" *ngIf="section.questions.length > 0">({{ section.questions.length }} questions)</span>
          </h2>
          <svg class="chevron" [class.expanded]="isSectionExpanded(section.unitKey)" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <polyline points="6 9 12 15 18 9"/>
          </svg>
        </div>
        <p *ngIf="section.description" class="section-description">{{ section.description }}</p>
        
        <!-- Section Progress -->
        <div class="section-progress" *ngIf="section.questions.length > 0">
          <div class="progress-bar-mini">
            <div class="progress-fill-mini" 
                 [style.width.%]="getSectionProgress(section)"
                 [class.completed]="getSectionProgress(section) === 100"></div>
          </div>
          <span class="section-progress-text">{{ getSectionCompletedCount(section) }}/{{ section.questions.length }} completed</span>
        </div>
      </div>
      
      <div class="questions-list" *ngIf="isSectionExpanded(section.unitKey) && section.questions.length > 0">
        <div
          *ngFor="let question of section.questions"
          class="question-item"
          [class.completed]="isQuestionCompleted(question.filename)"
          (click)="onQuestionClick(question)"
        >
          <div class="question-content">
            <div class="tags-container" *ngIf="question.tags && question.tags.length > 0">
              <span
                *ngFor="let tag of question.tags"
                class="difficulty-tag"
                [style.background-color]="tag.color + '20'"
                [style.color]="tag.color"
                [style.border]="'1px solid ' + tag.color + '40'"
              >
                {{ tag.text }}
              </span>
            </div>
            <h3>{{ question.title }}</h3>
          </div>
          <div class="question-actions">
            <button
              *ngFor="let urlItem of question.urls"
              class="url-btn"
              [style.background-color]="urlItem.color + '40'"
              [style.border]="'1px solid ' + urlItem.color + '60'"
              [style.color]="urlItem.color"
              (click)="onUrlClick($event, urlItem.url)"
              [title]="urlItem.tooltip"
            >
              <svg 
                xmlns="http://www.w3.org/2000/svg" 
                height="16" 
                viewBox="0 -960 960 960" 
                width="16" 
                class="link-icon"
              >
                <path d="M440-280H280q-83 0-141.5-58.5T80-480q0-83 58.5-141.5T280-680h160v80H280q-50 0-85 35t-35 85q0 50 35 85t85 35h160v80ZM320-440v-80h320v80H320Zm200 160v-80h160q50 0 85-35t35-85q0-50-35-85t-85-35H520v-80h160q83 0 141.5 58.5T880-480q0 83-58.5 141.5T680-280H520Z"/>
              </svg>
            </button>
            <svg *ngIf="isQuestionCompleted(question.filename)" class="completion-check" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="20 6 9 17 4 12"/>
            </svg>
          </div>
        </div>
      </div>
      
      <div *ngIf="section.questions.length === 0" class="no-questions-in-section">
        <p>No questions in this section yet.</p>
      </div>
    </div>
  </div>
  
  <div *ngIf="courseSections.length === 0 && course" class="no-sections">
    <p>No sections found in this course.</p>
  </div>
</div>
