// react/src/pages/Home.tsx
import { useNavigate } from 'react-router-dom';
import { useCallback, useState, useEffect } from 'react';
import { Code, BookOpen, Zap, Target, ArrowRight } from 'lucide-react';
import './Home.css';

export function Home() {
  const navigate = useNavigate();
  const [questionsIndex, setQuestionsIndex] = useState<{ questions: { filename: string }[] } | null>(null);
  const [coursesIndex, setCoursesIndex] = useState<{ courses: { filename: string }[] } | null>(null);

  useEffect(() => {
    fetch('/questions/index.json')
      .then(res => res.json())
      .then(setQuestionsIndex)
      .catch(console.error);

    fetch('/courses/index.json')
      .then(res => res.json())
      .then(setCoursesIndex)
      .catch(console.error);
  }, []);

  const navigateToRandomQuestion = useCallback(() => {
    if (questionsIndex && questionsIndex.questions.length > 0) {
      const randomIndex = Math.floor(Math.random() * questionsIndex.questions.length);
      const randomQuestion = questionsIndex.questions[randomIndex];
      navigate(`/questions/${randomQuestion.filename}`);
    } else {
      navigate('/questions/two-sum');
    }
  }, [navigate, questionsIndex]);

  const navigateToRandomCourse = useCallback(() => {
    if (coursesIndex && coursesIndex.courses.length > 0) {
      const randomIndex = Math.floor(Math.random() * coursesIndex.courses.length);
      const randomCourse = coursesIndex.courses[randomIndex];
      navigate(`/courses/${randomCourse.filename}`);
    } else {
      navigate('/courses');
    }
  }, [navigate, coursesIndex]);

  return (
    <div className="home">
      <section className="hero">
        <div className="hero-content">
          <h1 className="hero-title">
            Master Algorithms,
            <br />
            <span className="highlight">One Problem at a Time</span>
          </h1>
          <p className="hero-description">
            Practice coding challenges with instant feedback. Build your skills
            with curated problem sets and structured learning paths.
          </p>
          <div className="hero-actions">
            <button className="btn btn-primary btn-lg" onClick={navigateToRandomQuestion}>
              <Code size={20} />
              Start Coding
              <ArrowRight size={20} />
            </button>
            <button className="btn btn-secondary btn-lg" onClick={() => navigate('/courses')}>
              <BookOpen size={20} />
              Browse Courses
            </button>
          </div>
        </div>
      </section>

      <section className="features">
        <div className="features-grid">
          <div className="feature-card" onClick={navigateToRandomQuestion}>
            <div className="feature-icon">
              <Zap size={24} />
            </div>
            <h3>Practice Problems</h3>
            <p>Jump into a random problem and start coding. Real-time Python execution in your browser.</p>
          </div>

          <div className="feature-card" onClick={() => navigate('/courses')}>
            <div className="feature-icon">
              <BookOpen size={24} />
            </div>
            <h3>Structured Courses</h3>
            <p>Follow curated learning paths organized by topic. Track your progress as you go.</p>
          </div>

          <div className="feature-card" onClick={navigateToRandomCourse}>
            <div className="feature-icon">
              <Target size={24} />
            </div>
            <h3>Explore a Course</h3>
            <p>Discover a random course to challenge yourself. From foundations to advanced topics.</p>
          </div>
        </div>
      </section>

      <section className="cta">
        <div className="cta-content">
          <h2>Ready to Level Up?</h2>
          <p>Start your journey to mastering algorithms today.</p>
          <button className="btn btn-primary btn-lg" onClick={navigateToRandomQuestion}>
            Get Started
            <ArrowRight size={20} />
          </button>
        </div>
      </section>
    </div>
  );
}

// src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-home',
  imports: [],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent {
  constructor(private router: Router, private http: HttpClient) {}

  navigateToQuestions() {
    this.router.navigate(['/questions']);
  }

  navigateToCourses() {
    this.router.navigate(['/courses']);
  }

  navigateToRandomQuestion() {
    // Load questions index and navigate to random question
    this.http.get<any>('/questions/index.json').subscribe({
      next: (data) => {
        if (data.questions && data.questions.length > 0) {
          const randomIndex = Math.floor(Math.random() * data.questions.length);
          const randomQuestion = data.questions[randomIndex];
          this.router.navigate(['/questions', randomQuestion.filename]);
        } else {
          this.router.navigate(['/questions']);
        }
      },
      error: () => {
        // Fallback to questions page if index can't be loaded
        this.router.navigate(['/questions']);
      }
    });
  }

  navigateToRandomCourse() {
    // Load courses index and navigate to random course
    this.http.get<any>('/courses/index.json').subscribe({
      next: (data) => {
        if (data.courses && data.courses.length > 0) {
          const randomIndex = Math.floor(Math.random() * data.courses.length);
          const randomCourse = data.courses[randomIndex];
          this.router.navigate(['/courses', randomCourse.filename]);
        } else {
          this.router.navigate(['/courses']);
        }
      },
      error: () => {
        // Fallback to courses page if index can't be loaded
        this.router.navigate(['/courses']);
      }
    });
  }
}

<div class="landing-container">
  <!-- Hero Section -->
  <section class="hero-section">

    <div class="hero-content">
  <h1 class="hero-title">
    Master Algorithms & 
    <span class="gradient-text">Data Structures</span>
  </h1>

  <p class="hero-subtitle">
    Practice coding interviews with interactive challenges, real-time execution, 
    and detailed solutions. Join thousands of developers improving their skills.
  </p>

  <div class="hero-buttons">
    <button class="hero-cta-primary" (click)="navigateToRandomQuestion()">
      <span class="button-icon">💻</span>
      Random Question
    </button>
    <button class="hero-cta-secondary" (click)="navigateToRandomCourse()">
      <span class="button-icon">📚</span>
      Random Course
    </button>
  </div>

  <div class="hero-stats">
    <div class="stat-item">
      <div class="stat-number">500+</div>
      <div class="stat-label">Challenges</div>
    </div>
    <div class="stat-divider"></div>
    <div class="stat-item">
      <div class="stat-number">10K+</div>
      <div class="stat-label">Solutions</div>
    </div>
    <div class="stat-divider"></div>
    <div class="stat-item">
      <div class="stat-number">4</div>
      <div class="stat-label">Languages</div>
    </div>
  </div>
</div>
    <div class="hero-visual">
      <div class="code-preview">
        <div class="code-header">
          <div class="code-dots">
            <span class="dot red"></span>
            <span class="dot yellow"></span>
            <span class="dot green"></span>
          </div>
          <span class="code-title">two_sum.py</span>
        </div>
        <div class="code-content">
          <div class="code-line">
            <span class="line-number">1</span>
            <span class="code-text"><span class="keyword">def</span>&nbsp;<span class="function">twoSum</span>(<span class="param">nums, target</span>):</span>
          </div>
          <div class="code-line">
            <span class="line-number">2</span>
            <span class="code-text">&nbsp;&nbsp;&nbsp;&nbsp;<span class="variable">seen</span>&nbsp;=&nbsp;{{ '{' }}{{ '}' }}</span>
          </div>
          <div class="code-line">
            <span class="line-number">3</span>
            <span class="code-text">&nbsp;&nbsp;&nbsp;&nbsp;<span class="keyword">for</span>&nbsp;<span class="variable">i</span>,&nbsp;<span class="variable">num</span>&nbsp;<span class="keyword">in</span>&nbsp;<span class="function">enumerate</span>(<span class="param">nums</span>):</span>
          </div>
          <div class="code-line">
            <span class="line-number">4</span>
            <span class="code-text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="variable">diff</span>&nbsp;=&nbsp;<span class="param">target</span>&nbsp;-&nbsp;<span class="variable">num</span></span>
          </div>
          <div class="code-line">
            <span class="line-number">5</span>
            <span class="code-text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="keyword">if</span>&nbsp;<span class="variable">diff</span>&nbsp;<span class="keyword">in</span>&nbsp;<span class="variable">seen</span>:</span>
          </div>
          <div class="code-line">
            <span class="line-number">6</span>
            <span class="code-text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="keyword">return</span>&nbsp;&#91;<span class="variable">seen</span>&#91;<span class="variable">diff</span>&#93;,&nbsp;<span class="variable">i</span>&#93;</span>
          </div>
          <div class="code-line">
            <span class="line-number">7</span>
            <span class="code-text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="variable">seen</span>&#91;<span class="variable">num</span>&#93;&nbsp;=&nbsp;<span class="variable">i</span></span>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Features Section -->
  <section class="features-section">
    <div class="section-header">
      <h2 class="section-title">Why Choose AlgoLounge?</h2>
      <p class="section-subtitle">Everything you need to ace your coding interviews</p>
    </div>
    <div class="features-grid">
      <div class="feature-card">
        <div class="feature-icon">⚡</div>
        <h3 class="feature-title">Real-time Execution</h3>
        <p class="feature-description">Test your solutions instantly with our integrated code editor and execution environment.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">🎯</div>
        <h3 class="feature-title">Interview-focused</h3>
        <p class="feature-description">Practice problems commonly asked at top tech companies like Google, Amazon, and Microsoft.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">📈</div>
        <h3 class="feature-title">Track Progress</h3>
        <p class="feature-description">Monitor your improvement with detailed analytics and completion tracking.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">🔧</div>
        <h3 class="feature-title">Multiple Languages</h3>
        <p class="feature-description">Code in Python, JavaScript, TypeScript, and Java with full syntax highlighting.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">💡</div>
        <h3 class="feature-title">Detailed Solutions</h3>
        <p class="feature-description">Learn from comprehensive explanations and optimized solutions for every problem.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon">🚀</div>
        <h3 class="feature-title">Structured Learning</h3>
        <p class="feature-description">Follow curated courses that build your skills from basics to advanced concepts.</p>
      </div>
    </div>
  </section>

  <!-- CTA Section -->
  <section class="cta-section">
    <div class="cta-content">
      <h2 class="cta-title">Ready to Level Up Your Coding Skills?</h2>
      <p class="cta-subtitle">Join thousands of developers who've improved their problem-solving abilities</p>
      <button class="cta-final" (click)="navigateToCourses()">
        Discover Courses
      </button>
    </div>
  </section>
</div>
