// react/src/pages/Questions.tsx
import { useState, useEffect, useRef, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Sidebar } from '../components/Sidebar';
import { IDE, IDEHandle } from '../components/IDE';
import { Console } from '../components/Console';
import { ContentTabs } from '../components/ContentTabs';
import { SuccessAnimation } from '../components/SuccessAnimation';
import { useCodeExecution } from '../hooks/useCodeExecution';
import { useTags } from '../hooks/useTags';
import { useCompletion } from '../context/CompletionContext';
import { useSidebar } from '../context/SidebarContext';
import { Question, ExecutionResult, Tag } from '../types';
import './Questions.css';

export function Questions() {
  const { name } = useParams<{ name: string }>();
  const navigate = useNavigate();
  const ideRef = useRef<IDEHandle>(null);
  const { executeCode, stopExecution, initPyodide, isLoading } = useCodeExecution();
  const { getQuestionTags } = useTags();
  const { isCompleted, markCompleted } = useCompletion();
  const { isVisible: sidebarVisible } = useSidebar();

  const [question, setQuestion] = useState<Question | null>(null);
  const [executionResult, setExecutionResult] = useState<ExecutionResult | null>(null);
  const [isRunning, setIsRunning] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [notFound, setNotFound] = useState(false);
  const [questionTags, setQuestionTags] = useState<Tag[]>([]);

  const currentFilename = name || '';
  const completed = isCompleted(currentFilename);

  // Load question data
  useEffect(() => {
    if (!name) return;

    setNotFound(false);
    setExecutionResult(null);

    fetch(`/questions/${name}.json`)
      .then(res => {
        if (!res.ok) throw new Error('Not found');
        return res.json();
      })
      .then((data: Question) => {
        setQuestion(data);
        setQuestionTags(getQuestionTags(data.difficulty, data.tags));
        // Preload Pyodide
        initPyodide().catch(console.warn);
      })
      .catch(() => {
        setNotFound(true);
      });
  }, [name, getQuestionTags, initPyodide]);

  const handleRun = useCallback(async () => {
    if (!ideRef.current || !question) return;

    setIsRunning(true);
    setExecutionResult(null);

    try {
      const code = ideRef.current.getCode();
      const result = await executeCode(
        code,
        question.test_cases,
        question.entry_function,
        question.prepare,
        question.verify
      );

      setExecutionResult(result);

      // Check if all tests passed
      if (result.passedCount === result.totalCount && result.totalCount > 0) {
        if (!completed) {
          await markCompleted(currentFilename);
        }
        setShowSuccess(true);
      }
    } catch (error) {
      console.error('Execution error:', error);
      setExecutionResult({
        testResults: [{
          id: 1,
          input: {},
          expectedOutput: null,
          actualOutput: null,
          passed: false,
          error: error instanceof Error ? error.message : String(error),
          output: []
        }],
        executionTime: 0,
        passedCount: 0,
        totalCount: 1,
        output: []
      });
    } finally {
      setIsRunning(false);
    }
  }, [question, executeCode, completed, markCompleted, currentFilename]);

  const handleStop = useCallback(() => {
    stopExecution();
    setIsRunning(false);
  }, [stopExecution]);

  const handleReset = useCallback(() => {
    setExecutionResult(null);
  }, []);

  if (notFound) {
    return (
      <div className="questions-page">
        <div className="not-found">
          <h2>Question Not Found</h2>
          <p>The question "{name}" doesn't exist.</p>
          <button className="btn btn-primary" onClick={() => navigate('/questions/two-sum')}>
            Go to Two Sum
          </button>
        </div>
      </div>
    );
  }

  if (!question) {
    return (
      <div className="questions-page">
        <div className="loading">
          <div className="spinner" />
          <span>Loading question...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="questions-page">
      <SuccessAnimation show={showSuccess} onComplete={() => setShowSuccess(false)} />

      <Sidebar currentQuestionFilename={currentFilename} />

      <main className={`questions-main ${!sidebarVisible ? 'full-width' : ''}`}>
        <div className="questions-layout">
          <div className="left-panel">
            <ContentTabs
              description={question.description}
              solutionText={question.solution_text}
              solutionCode={question.solution_code}
              questionTags={questionTags}
              isCompleted={completed}
            />
          </div>

          <div className="right-panel">
            <div className="ide-container">
              <IDE
                ref={ideRef}
                template={question.template}
                isRunning={isRunning}
                onRun={handleRun}
                onStop={handleStop}
                onReset={handleReset}
              />
            </div>
            <div className="console-container">
              <Console result={executionResult} isRunning={isRunning} />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

// frontend/src/app/pages/questions/questions.component.ts
import { Component, OnInit, OnDestroy, ViewChild, signal } from "@angular/core";
import { IdeComponent } from "./ide/ide.component";
import { ConsoleComponent, ExecutionResult } from "./console/console.component";
import { ContentTabsComponent } from "../../components/general/content-tabs.component";
import { SidebarComponent } from "../../components/general/sidebar/sidebar.component";
import { SplitterModule } from "primeng/splitter";
import { ActivatedRoute, Router } from "@angular/router";
import { CommonModule } from "@angular/common";
import { HttpClient } from "@angular/common/http";
import { NotFoundComponent } from "../not-found/not-found.component";
import { CodeExecutionService } from "../../services/code-execution.service";
import { LocalStorageService } from "../../services/local-storage.service";
import { CompletionService } from "../../services/completion.service";
import { AuthService } from "../../services/auth.service";
import { TagService, Tag } from "../../services/tag.service";
import { SidebarService } from "../../services/sidebar.service";
import { SuccessAnimationComponent } from "../../components/questions/success-animation/success-animation.component";
import { Subject } from "rxjs";
import { takeUntil } from "rxjs/operators";

@Component({
  selector: "app-questions",
  standalone: true,
  imports: [
    CommonModule,
    IdeComponent,
    ConsoleComponent,
    ContentTabsComponent,
    SidebarComponent,
    SplitterModule,
    NotFoundComponent,
    SuccessAnimationComponent,
  ],
  templateUrl: "./questions.component.html",
  styleUrl: "./questions.component.scss",
})
export class QuestionsComponent implements OnInit, OnDestroy {
  @ViewChild(IdeComponent) ideComponent!: IdeComponent;

  description: string = "";
  solutionText: string = "";
  solutionCode: string = "";
  questionData: any = null;
  template: string = "";
  executionResult: ExecutionResult | null = null;
  isRunning: boolean = false;
  horizontalPanelSizes: number[] = [40, 60];
  sidebarOpenPanelSizes: number[] = [20, 30, 50]; // sidebar, content-tabs, ide+console
  verticalPanelSizes: number[] = [65, 35];
  currentQuestionFilename: string = "";
  isCompleted: boolean = false;
  showSuccessAnimation = signal(false);
  questionTags: Tag[] = [];
  sidebarVisible: boolean = true;
  private destroy$ = new Subject<void>();

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private http: HttpClient,
    private codeExecutionService: CodeExecutionService,
    private localStorageService: LocalStorageService,
    private completionService: CompletionService,
    private authService: AuthService,
    private tagService: TagService,
    private sidebarService: SidebarService
  ) {}

  ngOnInit() {
    // Add questions-page class to body
    document.body.classList.add('questions-page');

    // Subscribe to sidebar visibility
    this.sidebarService.sidebarVisible$.pipe(takeUntil(this.destroy$)).subscribe(visible => {
      this.sidebarVisible = visible;
    });

    // Load completions if authenticated
    if (this.authService.isAuthenticated()) {
      this.completionService.getCompletions().pipe(takeUntil(this.destroy$)).subscribe({
        next: () => {
          // After completions loaded, check current question completion
          if (this.currentQuestionFilename) {
            this.checkCompletion(this.currentQuestionFilename);
          }
        },
        error: () => {
          // Fallback to local storage on error
        }
      });
    }

    this.route.paramMap.pipe(takeUntil(this.destroy$)).subscribe((params) => {
      const name = params.get("name");
      if (name) {
        this.currentQuestionFilename = name;
        // Check completion immediately (will be updated after backend loads)
        this.checkCompletion(name);
        this.loadQuestion(name);
      }
    });
  }

  ngOnDestroy() {
    // Remove questions-page class when leaving
    document.body.classList.remove('questions-page');
    this.destroy$.next();
    this.destroy$.complete();
  }

  private checkCompletion(questionFilename: string) {
    // Check backend first if authenticated, fallback to localStorage
    if (this.authService.isAuthenticated()) {
      this.isCompleted = this.completionService.isCompleted(questionFilename);
    } else {
      this.isCompleted = this.localStorageService.isQuestionCompleted(questionFilename);
    }
  }

  onGo(name: string) {
    this.router.navigate(["/questions", name]);
  }


  async onRun() {
    if (!this.ideComponent || !this.questionData) {
      return;
    }

    this.isRunning = true;
    this.executionResult = null;

    try {
      const code = this.ideComponent.getCode();
      const functionName = this.questionData.entry_function || 'function';
      const testCases = this.questionData.test_cases || [];

      this.executionResult = await this.codeExecutionService.executeCode(
        code,
        testCases,
        functionName,
        this.questionData.prepare, // Pass prepare code
        this.questionData.verify   // Pass verify code
      );

      // Check if all tests passed and mark as completed
      if (this.executionResult.passedCount === this.executionResult.totalCount && this.executionResult.totalCount > 0) {
        // Mark as completed if not already
        if (!this.isCompleted) {
          this.isCompleted = true;

          // If authenticated, mark on backend; otherwise use local storage
          if (this.authService.isAuthenticated()) {
            this.completionService.markCompleted(this.currentQuestionFilename).pipe(takeUntil(this.destroy$)).subscribe({
              error: (err) => {
                console.error('Error marking question as completed:', err);
                // Fallback to local storage on error
                this.localStorageService.addCompletedQuestion(this.currentQuestionFilename);
              }
            });
          } else {
            this.localStorageService.addCompletedQuestion(this.currentQuestionFilename);
          }
        }
        // Trigger success animation every time all tests pass
        console.log('All tests passed! Triggering success animation');
        this.showSuccessAnimation.set(true);
      } else {
        console.log('Not all tests passed:', this.executionResult.passedCount, '/', this.executionResult.totalCount);
      }
    } catch (error) {
      console.error('Execution error:', error);
      this.executionResult = {
        testResults: [],
        executionTime: 0,
        passedCount: 0,
        totalCount: 0,
        output: [`Error: ${error instanceof Error ? error.message : String(error)}`]
      };
    } finally {
      this.isRunning = false;
    }
  }

  onStop() {
    this.codeExecutionService.stopExecution();
    this.isRunning = false;
  }

  onReset() {
    // Clear console output when reset button is clicked
    this.executionResult = null;
  }

  notFound = false;

  loadQuestion(name: string) {
    this.notFound = false;
    this.executionResult = null;  // Clear console output when loading new question
    this.http
      .get<any>(`/questions/${name}.json`)
      .subscribe({
        next: (data) => {
          this.questionData = data;
          this.updateQuestionContent();
          this.notFound = false;
          // Preload Pyodide to reduce first-run delay
          this.preloadPyodide();
        },
        error: () => {
          this.notFound = true;
        },
      });
  }

  updateQuestionContent() {
    if (!this.questionData) return;

    // Python-only format
    this.description = this.questionData.description || "";
    this.solutionText = this.questionData.solution_text || "";
    this.solutionCode = this.questionData.solution_code || "";
    this.template = this.questionData.template || "";

    // Extract difficulty and tags
    const difficulty = this.questionData.difficulty;
    const tags = this.questionData.tags || [];

    // Convert to Tag objects with colors
    this.questionTags = this.tagService.getQuestionTags(difficulty, tags);

    // Validate that entry_function is provided
    if (!this.questionData.entry_function) {
      console.warn(`Question ${this.currentQuestionFilename} is missing entry_function field`);
    }
  }


  onHorizontalResizeEnd(event: any) {
    this.horizontalPanelSizes = event.sizes;
  }

  onVerticalResizeEnd(event: any) {
    this.verticalPanelSizes = event.sizes;
  }

  private async preloadPyodide() {
    try {
      await this.codeExecutionService.initPyodide();
    } catch (error) {
      console.warn('Failed to preload Pyodide:', error);
    }
  }

  onSuccessAnimationComplete() {
    this.showSuccessAnimation.set(false);
  }
}

<ng-container *ngIf="!notFound; else notFoundTpl">
  <p-splitter
    [style]="{ height: 'calc(100%)', margin: '0' }"
    [panelSizes]="horizontalPanelSizes"
    [minSizes]="[25, 10]"
    (onResizeEnd)="onHorizontalResizeEnd($event)"
  >
    <ng-template pTemplate="panel1">
      <app-content-tabs
        [description]="description"
        [solutionText]="solutionText"
        [solutionCode]="solutionCode"
        [isCompleted]="isCompleted"
        [currentQuestionFilename]="currentQuestionFilename"
        [questionTags]="questionTags"
        (go)="onGo($event)">
      </app-content-tabs>
    </ng-template>
    <ng-template pTemplate="panel2">
      <p-splitter layout="vertical" [panelSizes]="verticalPanelSizes" [minSizes]="[10, 5]" (onResizeEnd)="onVerticalResizeEnd($event)">
        <ng-template pTemplate="panel1">
          <app-ide
            [template]="template"
            [questionData]="questionData"
            [isRunning]="isRunning"
            (run)="onRun()"
            (stop)="onStop()"
            (reset)="onReset()"
          ></app-ide>
        </ng-template>
        <ng-template pTemplate="panel2">
          <app-console [result]="executionResult" [isRunning]="isRunning"></app-console>
        </ng-template>
      </p-splitter>
    </ng-template>
  </p-splitter>

  <!-- Success Animation -->
  <app-success-animation
    *ngIf="showSuccessAnimation()"
    (animationComplete)="onSuccessAnimationComplete()">
  </app-success-animation>
</ng-container>
<ng-template #notFoundTpl>
  <app-not-found></app-not-found>
</ng-template>
