// react/src/components/Console.tsx
import { ExecutionResult, TestResult } from '../types';
import { CheckCircle, XCircle, Clock, Terminal } from 'lucide-react';
import './Console.css';

interface ConsoleProps {
  result: ExecutionResult | null;
  isRunning: boolean;
}

function formatValue(value: unknown): string {
  if (Array.isArray(value)) {
    return JSON.stringify(value);
  }
  if (typeof value === 'object' && value !== null) {
    return JSON.stringify(value);
  }
  return String(value);
}

function TestResultItem({ test }: { test: TestResult }) {
  return (
    <div className={`test-result ${test.passed ? 'passed' : 'failed'}`}>
      <div className="test-header">
        <div className="test-status">
          {test.passed ? (
            <CheckCircle size={16} className="status-icon success" />
          ) : (
            <XCircle size={16} className="status-icon error" />
          )}
          <span className="test-label">Test {test.id}</span>
        </div>
        <span className={`test-badge ${test.passed ? 'success' : 'error'}`}>
          {test.passed ? 'Passed' : 'Failed'}
        </span>
      </div>

      <div className="test-details">
        <div className="test-row">
          <span className="test-key">Input:</span>
          <code className="test-value">{formatValue(test.input)}</code>
        </div>
        <div className="test-row">
          <span className="test-key">Expected:</span>
          <code className="test-value">{formatValue(test.expectedOutput)}</code>
        </div>
        <div className="test-row">
          <span className="test-key">Output:</span>
          <code className={`test-value ${test.passed ? '' : 'error-text'}`}>
            {test.error ? test.error : formatValue(test.actualOutput)}
          </code>
        </div>

        {test.output && test.output.length > 0 && (
          <div className="test-row">
            <span className="test-key">Console:</span>
            <div className="test-console">
              {test.output.map((line, i) => (
                <div key={i} className="console-line">{line}</div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export function Console({ result, isRunning }: ConsoleProps) {
  if (isRunning) {
    return (
      <div className="console">
        <div className="console-header">
          <Terminal size={16} />
          <span>Console</span>
        </div>
        <div className="console-content">
          <div className="console-loading">
            <div className="spinner" />
            <span>Running tests...</span>
          </div>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="console">
        <div className="console-header">
          <Terminal size={16} />
          <span>Console</span>
        </div>
        <div className="console-content">
          <div className="console-empty">
            <Terminal size={24} className="empty-icon" />
            <p>Click "Run" to execute your code and see results</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="console">
      <div className="console-header">
        <Terminal size={16} />
        <span>Console</span>
        <div className="console-summary">
          <span className={`summary-text ${result.passedCount === result.totalCount ? 'success' : 'error'}`}>
            {result.passedCount}/{result.totalCount} tests passed
          </span>
          <span className="summary-time">
            <Clock size={14} />
            {result.executionTime}ms
          </span>
        </div>
      </div>
      <div className="console-content">
        <div className="test-results">
          {result.testResults.map((test) => (
            <TestResultItem key={test.id} test={test} />
          ))}
        </div>
      </div>
    </div>
  );
}

// src/app/pages/questions/console/console.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface TestResult {
  id: number;
  input: any;
  expectedOutput: any;
  actualOutput: any;
  passed: boolean;
  error?: string;
  output?: string[];
}

export interface ExecutionResult {
  testResults: TestResult[];
  executionTime: number;
  passedCount: number;
  totalCount: number;
  output: string[];
}

@Component({
  selector: 'app-console',
  imports: [CommonModule],
  templateUrl: './console.component.html',
  styleUrl: './console.component.scss'
})
export class ConsoleComponent {
  @Input() result: ExecutionResult | null = null;
  @Input() isRunning: boolean = false;

  formatValue(value: any): string {
    if (Array.isArray(value)) {
      return JSON.stringify(value);
    }
    if (typeof value === 'object' && value !== null) {
      return JSON.stringify(value);
    }
    return String(value);
  }
}

<div class="console-container" *ngIf="result; else emptyConsole">
  <!-- Enhanced Summary Section -->
  <div class="summary-header">
    <div class="summary-stats">
      <div class="stat-box time">
        <div class="stat-value">{{ result.executionTime }}<span class="stat-unit">ms</span></div>
        <div class="stat-label">EXECUTION TIME</div>
      </div>
      <div class="stat-box tests" [ngClass]="{ 'all-passed': result.passedCount === result.totalCount, 'some-failed': result.passedCount < result.totalCount }">
        <div class="stat-value">{{ result.passedCount }}/{{ result.totalCount }}</div>
        <div class="stat-label">TESTS PASSED</div>
      </div>
    </div>
  </div>

  <!-- Compact Test Results -->
  <div class="test-results-compact">
    <div
      *ngFor="let testResult of result.testResults"
      class="test-row"
    >
      <div class="test-content">
        <div class="test-header-compact">
          <span class="test-number">Test {{ testResult.id }}</span>
          <span class="test-badge" [ngClass]="{ 'badge-pass': testResult.passed, 'badge-fail': !testResult.passed }">
            {{ testResult.passed ? 'PASS' : 'FAIL' }}
          </span>
        </div>

        <div class="test-details" *ngIf="!testResult.error">
          <div class="detail-row">
            <span class="detail-label">INPUT:</span>
            <code class="detail-value">{{ formatValue(testResult.input) }}</code>
          </div>
          <div class="detail-row">
            <span class="detail-label">EXPECTED:</span>
            <code class="detail-value expected">{{ formatValue(testResult.expectedOutput) }}</code>
          </div>
          <div class="detail-row">
            <span class="detail-label">ACTUAL:</span>
            <code class="detail-value actual">{{ formatValue(testResult.actualOutput) }}</code>
          </div>
        </div>

        <div class="error-message" *ngIf="testResult.error">
          <div class="error-icon">⚠</div>
          <div class="error-text">{{ testResult.error }}</div>
        </div>

        <div *ngIf="testResult.output && testResult.output.length > 0" class="console-output">
          <div class="output-header">CONSOLE OUTPUT:</div>
          <div class="output-lines">
            <div *ngFor="let line of testResult.output" class="output-line">{{ line }}</div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

<ng-template #emptyConsole>
  <div class="console-container empty">
    <div *ngIf="isRunning" class="running-state">
      <div class="spinner"></div>
      <div class="running-message">Running your code...</div>
    </div>
    <div *ngIf="!isRunning" class="empty-message">
      Click Run to execute your code and see test results here.
    </div>
  </div>
</ng-template>
