// react/src/pages/Courses.tsx
import { useState, useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useCourseSearch } from '../hooks/useCourseSearch';
import { useFavorites } from '../context/FavoritesContext';
import { useAuth } from '../context/AuthContext';
import { CourseSearchResult } from '../types';
import { Search, X, Heart, BookOpen } from 'lucide-react';
import './Courses.css';

export function Courses() {
  const navigate = useNavigate();
  const { isLoaded, allCourses, searchCourses } = useCourseSearch();
  const { favorites, isFavorite, toggleFavorite } = useFavorites();
  const { isAuthenticated } = useAuth();

  const [searchTerm, setSearchTerm] = useState('');
  const [showingFavorites, setShowingFavorites] = useState(false);

  const favoriteCourses = useMemo(() => {
    return allCourses.filter(c => favorites.includes(c.filename));
  }, [allCourses, favorites]);

  const displayResults = useMemo(() => {
    let results: CourseSearchResult[];

    if (showingFavorites) {
      results = searchTerm
        ? favoriteCourses.filter(c =>
            c.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
            c.filename.toLowerCase().includes(searchTerm.toLowerCase())
          )
        : favoriteCourses;
    } else {
      results = searchTerm ? searchCourses(searchTerm) : allCourses;
    }

    // Sort: favorites first, then alphabetically
    const favoriteFilenames = new Set(favorites);
    const favorited = results.filter(c => favoriteFilenames.has(c.filename));
    const nonFavorited = results.filter(c => !favoriteFilenames.has(c.filename));

    favorited.sort((a, b) => a.title.localeCompare(b.title));
    nonFavorited.sort((a, b) => a.title.localeCompare(b.title));

    return showingFavorites ? results : [...favorited, ...nonFavorited];
  }, [showingFavorites, searchTerm, favoriteCourses, allCourses, searchCourses, favorites]);

  const handleSelect = useCallback((course: CourseSearchResult) => {
    navigate(`/courses/${course.filename}`);
  }, [navigate]);

  const handleToggleFavorite = useCallback(async (e: React.MouseEvent, course: CourseSearchResult) => {
    e.stopPropagation();

    if (!isAuthenticated) {
      navigate('/auth/sign-in');
      return;
    }

    await toggleFavorite(course.filename);
  }, [isAuthenticated, navigate, toggleFavorite]);

  const getSearchResultText = () => {
    if (showingFavorites) {
      if (searchTerm) {
        return `Showing ${displayResults.length} of ${favoriteCourses.length} favorites`;
      }
      return `${favoriteCourses.length} ${favoriteCourses.length === 1 ? 'favorite' : 'favorites'}`;
    } else {
      if (searchTerm) {
        return `Showing ${displayResults.length} of ${allCourses.length} courses`;
      }
      return `${allCourses.length} ${allCourses.length === 1 ? 'course' : 'courses'}`;
    }
  };

  const getEmptyStateTitle = () => {
    if (showingFavorites && favoriteCourses.length === 0) {
      return 'No Favorites Yet';
    }
    if (showingFavorites && favoriteCourses.length > 0) {
      return 'No Matches Found';
    }
    if (searchTerm) {
      return `No results for "${searchTerm}"`;
    }
    return 'No Courses Found';
  };

  const getEmptyStateMessage = () => {
    if (showingFavorites && favoriteCourses.length === 0) {
      return 'Start building your personalized learning path by adding courses to your favorites. Click the heart icon on any course to get started.';
    }
    if (showingFavorites && favoriteCourses.length > 0) {
      return 'No favorites match your search. Try a different search term or clear the search to see all your favorites.';
    }
    if (searchTerm) {
      return 'Try adjusting your search term or browse all available courses.';
    }
    return 'No courses match your search. Try a different search term.';
  };

  return (
    <div className="courses-page">
      <div className="courses-header">
        <h1>Courses</h1>
        <p>Structured learning paths to master algorithms and data structures</p>
      </div>

      <div className="courses-toolbar">
        <div className="search-box">
          <Search size={16} className="search-icon" />
          <input
            type="text"
            placeholder="Search courses..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
          {searchTerm && (
            <button className="clear-search" onClick={() => setSearchTerm('')}>
              <X size={14} />
            </button>
          )}
        </div>

        <div className="filter-tabs">
          <button
            className={`filter-tab ${!showingFavorites ? 'active' : ''}`}
            onClick={() => setShowingFavorites(false)}
          >
            <BookOpen size={16} />
            All Courses
          </button>
          <button
            className={`filter-tab ${showingFavorites ? 'active' : ''}`}
            onClick={() => setShowingFavorites(true)}
          >
            <Heart size={16} />
            Favorites
          </button>
        </div>

        <div className="results-count">
          {getSearchResultText()}
        </div>
      </div>

      <div className="courses-content">
        {!isLoaded ? (
          <div className="courses-loading">
            <div className="spinner" />
            <span>Loading courses...</span>
          </div>
        ) : displayResults.length === 0 ? (
          <div className="courses-empty">
            <BookOpen size={48} className="empty-icon" />
            <h3>{getEmptyStateTitle()}</h3>
            <p>{getEmptyStateMessage()}</p>
          </div>
        ) : (
          <div className="courses-grid">
            {displayResults.map((course) => (
              <div
                key={course.filename}
                className="course-card"
                onClick={() => handleSelect(course)}
              >
                <div className="course-card-header">
                  <h3 className="course-title">{course.title}</h3>
                  <button
                    className={`favorite-btn ${isFavorite(course.filename) ? 'active' : ''}`}
                    onClick={(e) => handleToggleFavorite(e, course)}
                    aria-label={isFavorite(course.filename) ? 'Remove from favorites' : 'Add to favorites'}
                  >
                    <Heart size={18} fill={isFavorite(course.filename) ? 'currentColor' : 'none'} />
                  </button>
                </div>
                <p className="course-description">{course.description}</p>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// frontend/src/app/pages/courses/courses.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { CourseSearchService, CourseSearchResult } from '../../services/course-search.service';
import { FavoritesService } from '../../services/favorites.service';
import { AuthService } from '../../services/auth.service';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Component({
  selector: 'app-courses',
  imports: [CommonModule, FormsModule],
  templateUrl: './courses.component.html',
  styleUrl: './courses.component.scss'
})
export class CoursesComponent implements OnInit, OnDestroy {
  searchTerm = '';
  displayResults: CourseSearchResult[] = [];
  allCourses: CourseSearchResult[] = [];
  favoriteCourses: CourseSearchResult[] = [];
  showingFavorites = false;
  private destroy$ = new Subject<void>();

  constructor(
    private courseSearchService: CourseSearchService,
    private favoritesService: FavoritesService,
    private authService: AuthService,
    private router: Router,
    private http: HttpClient
  ) {}

  ngOnInit() {
    // Load courses
    this.courseSearchService.isIndexLoaded().pipe(takeUntil(this.destroy$)).subscribe(loaded => {
      if (loaded) {
        this.allCourses = this.courseSearchService.getAllCourses();
        this.displayResults = this.getSortedCourses(this.allCourses);
      }
    });

    // Load favorites if authenticated
    if (this.authService.isAuthenticated()) {
      this.favoritesService.getFavorites().pipe(takeUntil(this.destroy$)).subscribe({
        next: () => {
          this.updateFavoriteCourses();
        },
        error: () => {
          // Silently fail if not authenticated or error occurs
          this.updateFavoriteCourses();
        }
      });
    }
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  onSearchChange(event: any) {
    const query = event.target.value;
    this.searchTerm = query;
    if (this.showingFavorites) {
      this.displayResults = this.favoriteCourses.filter(c =>
        c.title.toLowerCase().includes(query.toLowerCase()) ||
        c.filename.toLowerCase().includes(query.toLowerCase())
      );
    } else {
      this.displayResults = this.courseSearchService.searchCourses(query);
    }
  }

  clearSearch() {
    this.searchTerm = '';
    if (this.showingFavorites) {
      this.displayResults = this.favoriteCourses;
    } else {
      this.displayResults = this.getSortedCourses(this.allCourses);
    }
  }

  getSearchResultText(): string {
    if (this.showingFavorites) {
      if (this.searchTerm) {
        return `Showing ${this.displayResults.length} of ${this.favoriteCourses.length} favorites`;
      }
      return `${this.favoriteCourses.length} ${this.favoriteCourses.length === 1 ? 'favorite' : 'favorites'}`;
    } else {
      if (this.searchTerm) {
        return `Showing ${this.displayResults.length} of ${this.allCourses.length} courses`;
      }
      return `${this.allCourses.length} ${this.allCourses.length === 1 ? 'course' : 'courses'}`;
    }
  }

  onSelect(course: CourseSearchResult) {
    this.router.navigate(['/courses', course.filename]);
  }

  isFavorite(course: CourseSearchResult): boolean {
    return this.favoritesService.isFavorite(course.filename);
  }

  toggleFavorite(course: CourseSearchResult, event: Event) {
    event.stopPropagation();

    if (!this.authService.isAuthenticated()) {
      this.router.navigate(['/sign-in']);
      return;
    }

    if (this.isFavorite(course)) {
      this.favoritesService.removeFavorite(course.filename).pipe(takeUntil(this.destroy$)).subscribe({
        next: () => {
          this.updateFavoriteCourses();
          if (!this.showingFavorites) {
            this.displayResults = this.getSortedCourses(this.allCourses);
          }
        },
        error: (err) => {
          console.error('Error removing favorite:', err);
        }
      });
    } else {
      this.favoritesService.addFavorite(course.filename).pipe(takeUntil(this.destroy$)).subscribe({
        next: () => {
          this.updateFavoriteCourses();
          if (!this.showingFavorites) {
            this.displayResults = this.getSortedCourses(this.allCourses);
          }
        },
        error: (err) => {
          console.error('Error adding favorite:', err);
        }
      });
    }
  }

  showFavorites() {
    this.showingFavorites = true;
    this.searchTerm = '';
    this.displayResults = this.favoriteCourses;
  }

  showAllCourses() {
    this.showingFavorites = false;
    this.searchTerm = '';
    this.displayResults = this.getSortedCourses(this.allCourses);
  }

  private updateFavoriteCourses() {
    const favoriteFilenames = this.favoritesService.getFavoritesSync();
    this.favoriteCourses = this.allCourses.filter(course =>
      favoriteFilenames.includes(course.filename)
    );
  }

  getEmptyStateTitle(): string {
    if (this.showingFavorites && this.favoriteCourses.length === 0) {
      return 'No Favorites Yet';
    }
    if (this.showingFavorites && this.favoriteCourses.length > 0) {
      return 'No Matches Found';
    }
    if (this.searchTerm) {
      return `No results for "${this.searchTerm}"`;
    }
    return 'No Courses Found';
  }

  getEmptyStateMessage(): string {
    if (this.showingFavorites && this.favoriteCourses.length === 0) {
      return 'Start building your personalized learning path by adding courses to your favorites. Click the heart icon on any course to get started.';
    }
    if (this.showingFavorites && this.favoriteCourses.length > 0) {
      return 'No favorites match your search. Try a different search term or clear the search to see all your favorites.';
    }
    if (this.searchTerm) {
      return 'Try adjusting your search term or browse all available courses.';
    }
    return 'No courses match your search. Try a different search term.';
  }

  private getSortedCourses(courses: CourseSearchResult[]): CourseSearchResult[] {
    const favoriteFilenames = this.favoritesService.getFavoritesSync();
    
    // Separate into favorited and non-favorited
    const favorited = courses.filter(c => favoriteFilenames.includes(c.filename));
    const nonFavorited = courses.filter(c => !favoriteFilenames.includes(c.filename));
    
    // Sort each group alphabetically by title
    favorited.sort((a, b) => a.title.localeCompare(b.title));
    nonFavorited.sort((a, b) => a.title.localeCompare(b.title));
    
    // Return favorited first, then non-favorited
    return [...favorited, ...nonFavorited];
  }
}

<div class="courses-page">
  <!-- Top Navigation Bar -->
  <div class="top-nav">
    <!-- Tabs on Left -->
    <div class="tabs">
      <button 
        class="tab-btn" 
        [class.active]="!showingFavorites"
        (click)="showAllCourses()"
      >
        All Courses
      </button>
      <button 
        class="tab-btn" 
        [class.active]="showingFavorites"
        (click)="showFavorites()"
      >
        Favorites ({{ favoriteCourses.length }})
      </button>
    </div>

    <!-- Search on Right -->
    <div class="search-container">
      <svg class="search-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="11" cy="11" r="8"/>
        <path d="m21 21-4.35-4.35"/>
      </svg>
      <input 
        type="text" 
        class="search-input"
        [placeholder]="showingFavorites ? 'Search favorites...' : 'Search academy...'"
        [(ngModel)]="searchTerm"
        (input)="onSearchChange($event)"
      />
      <button 
        *ngIf="searchTerm" 
        class="clear-btn" 
        (click)="clearSearch()"
        aria-label="Clear search"
      >
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="18" y1="6" x2="6" y2="18"/>
          <line x1="6" y1="6" x2="18" y2="18"/>
        </svg>
      </button>
    </div>
  </div>

  <!-- Result Count -->
  <p class="search-count" *ngIf="searchTerm || showingFavorites">
    {{ getSearchResultText() }}
  </p>
  
  <!-- Page Header -->
  <header class="page-header">
    <h1>ACADEMY</h1>
    <p class="subtitle">Structured learning paths to master algorithms and data structures</p>
  </header>
  
  <!-- Course Cards Grid -->
  <div class="courses-grid" *ngIf="displayResults.length > 0">
    <div *ngFor="let course of displayResults" class="course-card" (click)="onSelect(course)">
      <div class="card-header">
        <h3>{{ course.title }}</h3>
        <button
          class="favorite-btn"
          [class.favorited]="isFavorite(course)"
          (click)="toggleFavorite(course, $event)"
          [attr.aria-label]="isFavorite(course) ? 'Remove from favorites' : 'Add to favorites'"
        >
          <svg width="24" height="24" viewBox="0 0 24 24" [attr.fill]="isFavorite(course) ? 'currentColor' : 'none'" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
          </svg>
        </button>
      </div>
      <p class="card-description">{{ getCourseDescription(course) }}</p>
      <p class="card-stats" *ngIf="getCourseStats(course)">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/>
          <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/>
        </svg>
        {{ getCourseStats(course) }}
      </p>
      <div class="card-footer">
        <span class="badge" [class]="getCourseType(course)">{{ getBadgeText(course) }}</span>
      </div>
    </div>
  </div>
  
  <!-- Empty States -->
  <div *ngIf="displayResults.length === 0" class="empty-state">
    <svg *ngIf="!showingFavorites || (showingFavorites && favoriteCourses.length > 0)" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="11" cy="11" r="8"/>
      <path d="m21 21-4.35-4.35"/>
    </svg>
    <svg *ngIf="showingFavorites && favoriteCourses.length === 0" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
    </svg>
    <h3>{{ getEmptyStateTitle() }}</h3>
    <p>{{ getEmptyStateMessage() }}</p>
    <button 
      *ngIf="showingFavorites && favoriteCourses.length === 0" 
      class="btn-primary" 
      (click)="showAllCourses()"
    >
      Browse All Courses
    </button>
  </div>
</div>
