// react/src/components/Sidebar.tsx
import { useState, useMemo, useCallback, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuestionSearch } from '../hooks/useQuestionSearch';
import { useTags } from '../hooks/useTags';
import { useCompletion } from '../context/CompletionContext';
import { useSidebar } from '../context/SidebarContext';
import { QuestionSearchResult } from '../types';
import { Search, X, Check, ChevronDown, Tag } from 'lucide-react';
import './Sidebar.css';

interface SidebarProps {
  currentQuestionFilename: string;
}

export function Sidebar({ currentQuestionFilename }: SidebarProps) {
  const navigate = useNavigate();
  const { isLoaded, allQuestions, searchQuestions, getUniqueTags } = useQuestionSearch();
  const { getDifficultyColor, getTagColor } = useTags();
  const { isCompleted } = useCompletion();
  const { isVisible, close } = useSidebar();

  const [searchQuery, setSearchQuery] = useState('');
  const [selectedDifficulty, setSelectedDifficulty] = useState<string | null>(null);
  const [showCompleted, setShowCompleted] = useState<boolean | null>(null);
  const [selectedTag, setSelectedTag] = useState<string | null>(null);
  const [showTagsPopover, setShowTagsPopover] = useState(false);

  const tagsRef = useRef<HTMLDivElement>(null);

  const availableTags = useMemo(() => getUniqueTags(), [getUniqueTags]);

  const filteredQuestions = useMemo(() => {
    let result = searchQuery.trim() ? searchQuestions(searchQuery) : allQuestions;

    // Difficulty filter
    if (selectedDifficulty) {
      result = result.filter(q => q.difficulty.toLowerCase() === selectedDifficulty.toLowerCase());
    }

    // Tag filter
    if (selectedTag) {
      result = result.filter(q =>
        q.tags.some(tag => tag.toLowerCase() === selectedTag.toLowerCase())
      );
    }

    // Completion filter
    if (showCompleted !== null) {
      result = result.filter(q => {
        const completed = isCompleted(q.filename);
        return showCompleted ? completed : !completed;
      });
    }

    // Sort by difficulty, then by first tag
    const difficultyOrder: Record<string, number> = {
      'easy': 1,
      'medium': 2,
      'hard': 3
    };

    return result.sort((a, b) => {
      const diffA = difficultyOrder[a.difficulty.toLowerCase()] || 999;
      const diffB = difficultyOrder[b.difficulty.toLowerCase()] || 999;

      if (diffA !== diffB) return diffA - diffB;

      const tagA = a.tags[0]?.toLowerCase() || '';
      const tagB = b.tags[0]?.toLowerCase() || '';
      return tagA.localeCompare(tagB);
    });
  }, [allQuestions, searchQuestions, searchQuery, selectedDifficulty, selectedTag, showCompleted, isCompleted]);

  const toggleDifficulty = useCallback((difficulty: string) => {
    setSelectedDifficulty(prev => prev === difficulty ? null : difficulty);
  }, []);

  const toggleStatus = useCallback((completed: boolean) => {
    setShowCompleted(prev => prev === completed ? null : completed);
  }, []);

  const selectTag = useCallback((tag: string) => {
    setSelectedTag(tag);
    setShowTagsPopover(false);
  }, []);

  const clearTag = useCallback(() => {
    setSelectedTag(null);
    setShowTagsPopover(false);
  }, []);

  const handleSelect = useCallback((filename: string) => {
    navigate(`/questions/${filename}`);
    close();
  }, [navigate, close]);

  // Close popover when clicking outside
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (tagsRef.current && !tagsRef.current.contains(event.target as Node)) {
        setShowTagsPopover(false);
      }
    }

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const getDifficultyLabel = (difficulty: string) => {
    return difficulty.toLowerCase() === 'medium' ? 'Med' : difficulty;
  };

  if (!isVisible) return null;

  return (
    <div className="sidebar-overlay" onClick={close}>
      <aside className="sidebar" onClick={(e) => e.stopPropagation()}>
        <div className="sidebar-header">
          <div className="sidebar-title-row">
            <h2 className="sidebar-title">Problems</h2>
            <button className="sidebar-close" onClick={close}>
              <X size={20} />
            </button>
          </div>
          <div className="search-box">
          <Search size={16} className="search-icon" />
          <input
            type="text"
            placeholder="Search questions..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="search-input"
          />
          {searchQuery && (
            <button className="clear-search" onClick={() => setSearchQuery('')}>
              <X size={14} />
            </button>
          )}
        </div>

        <div className="filters">
          <div className="filter-group">
            {['Easy', 'Medium', 'Hard'].map((diff) => (
              <button
                key={diff}
                className={`filter-btn difficulty ${selectedDifficulty === diff ? 'active' : ''}`}
                style={{
                  '--difficulty-color': getDifficultyColor(diff)
                } as React.CSSProperties}
                onClick={() => toggleDifficulty(diff)}
              >
                {getDifficultyLabel(diff)}
              </button>
            ))}
          </div>

          <div className="filter-group">
            <button
              className={`filter-btn status ${showCompleted === true ? 'active' : ''}`}
              onClick={() => toggleStatus(true)}
            >
              <Check size={12} />
              Done
            </button>
            <button
              className={`filter-btn status ${showCompleted === false ? 'active' : ''}`}
              onClick={() => toggleStatus(false)}
            >
              Todo
            </button>
          </div>

          <div className="tags-section" ref={tagsRef}>
            <button
              className={`filter-btn tags-btn ${selectedTag ? 'active' : ''}`}
              onClick={() => setShowTagsPopover(!showTagsPopover)}
            >
              <Tag size={12} />
              {selectedTag || 'Tags'}
              <ChevronDown size={12} />
            </button>

            {showTagsPopover && (
              <div className="tags-popover">
                <button className="tag-option clear" onClick={clearTag}>
                  Clear Filter
                </button>
                {availableTags.map((tag) => (
                  <button
                    key={tag}
                    className={`tag-option ${selectedTag === tag ? 'selected' : ''}`}
                    onClick={() => selectTag(tag)}
                  >
                    <span
                      className="tag-dot"
                      style={{ backgroundColor: getTagColor(tag) }}
                    />
                    {tag}
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="results-count">
          {filteredQuestions.length} questions
        </div>
      </div>

      <div className="sidebar-content">
        {!isLoaded ? (
          <div className="sidebar-loading">
            <div className="spinner" />
          </div>
        ) : filteredQuestions.length === 0 ? (
          <div className="sidebar-empty">No questions found</div>
        ) : (
          <ul className="question-list">
            {filteredQuestions.map((question) => (
              <li key={question.filename}>
                <button
                  className={`question-item ${currentQuestionFilename === question.filename ? 'active' : ''}`}
                  onClick={() => handleSelect(question.filename)}
                >
                  <div className="question-info">
                    <span
                      className="question-difficulty"
                      style={{ color: getDifficultyColor(question.difficulty) }}
                    >
                      {getDifficultyLabel(question.difficulty)}
                    </span>
                    <span className="question-title">{question.title}</span>
                  </div>
                  {isCompleted(question.filename) && (
                    <Check size={14} className="completed-icon" />
                  )}
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>
    </aside>
    </div>
  );
}

// frontend/src/app/components/general/sidebar/sidebar.component.ts
import { Component, EventEmitter, HostListener, Input, OnInit, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { QuestionSearchService, QuestionSearchResult } from '../../../services/question-search.service';
import { LocalStorageService } from '../../../services/local-storage.service';
import { TagService } from '../../../services/tag.service';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnInit {
  @Input() currentQuestionFilename: string = '';
  @Output() selectQuestion = new EventEmitter<string>();

  searchQuery: string = '';
  questions: QuestionSearchResult[] = [];
  filteredQuestions: QuestionSearchResult[] = [];
  
  // Filters
  selectedDifficulty: string | null = null;
  showCompleted: boolean | null = null; // null = all, true = completed, false = todo
  selectedTag: string | null = null; // Single tag selection
  availableTags: string[] = []; // All unique tags from questions
  showTagsPopover: boolean = false; // Toggle popover visibility

  constructor(
    private questionSearchService: QuestionSearchService,
    private localStorageService: LocalStorageService,
    private tagService: TagService
  ) {}

  ngOnInit(): void {
    this.questionSearchService.isIndexLoaded().subscribe(loaded => {
      if (loaded) {
        this.questions = this.questionSearchService.getAllQuestions();
        this.availableTags = this.getAllUniqueTags();
        this.filterQuestions();
      }
    });
  }

  filterQuestions(): void {
    let result = this.questions;

    // Search filter
    if (this.searchQuery.trim()) {
      result = this.questionSearchService.searchQuestions(this.searchQuery);
    }

    // Difficulty filter
    if (this.selectedDifficulty) {
      result = result.filter(q => q.difficulty.toLowerCase() === this.selectedDifficulty?.toLowerCase());
    }

    // Tag filter - question must have the selected tag
    if (this.selectedTag) {
      result = result.filter(q =>
        q.tags.some(qTag => qTag.toLowerCase() === this.selectedTag?.toLowerCase())
      );
    }

    // Status filter
    if (this.showCompleted !== null) {
      result = result.filter(q => {
        const isCompleted = this.isQuestionCompleted(q.filename);
        return this.showCompleted ? isCompleted : !isCompleted;
      });
    }

    // Sort by difficulty first, then by tags
    result = this.sortQuestions(result);

    this.filteredQuestions = result;
  }

  private sortQuestions(questions: QuestionSearchResult[]): QuestionSearchResult[] {
    const difficultyOrder: { [key: string]: number } = {
      'easy': 1,
      'medium': 2,
      'hard': 3
    };

    return questions.sort((a, b) => {
      // First sort by difficulty
      const diffA = difficultyOrder[a.difficulty.toLowerCase()] || 999;
      const diffB = difficultyOrder[b.difficulty.toLowerCase()] || 999;

      if (diffA !== diffB) {
        return diffA - diffB;
      }

      // Then sort by first tag alphabetically
      const tagA = a.tags[0]?.toLowerCase() || '';
      const tagB = b.tags[0]?.toLowerCase() || '';

      return tagA.localeCompare(tagB);
    });
  }

  toggleDifficulty(difficulty: string): void {
    if (this.selectedDifficulty === difficulty) {
      this.selectedDifficulty = null;
    } else {
      this.selectedDifficulty = difficulty;
    }
    this.filterQuestions();
  }

  toggleStatus(completed: boolean): void {
    if (this.showCompleted === completed) {
      this.showCompleted = null;
    } else {
      this.showCompleted = completed;
    }
    this.filterQuestions();
  }

  selectTag(tag: string): void {
    this.selectedTag = tag;
    this.showTagsPopover = false;
    this.filterQuestions();
  }

  clearTag(): void {
    this.selectedTag = null;
    this.showTagsPopover = false;
    this.filterQuestions();
  }

  isTagSelected(tag: string): boolean {
    return this.selectedTag === tag;
  }

  getAllUniqueTags(): string[] {
    const tagSet = new Set<string>();
    this.questions.forEach(q => {
      q.tags.forEach(tag => tagSet.add(tag));
    });
    return Array.from(tagSet).sort();
  }

  isQuestionCompleted(filename: string): boolean {
    return this.localStorageService.isQuestionCompleted(filename);
  }

  onSelect(filename: string): void {
    this.selectQuestion.emit(filename);
  }

  getTagColor(tag: string): string {
    return this.tagService.getTagColor(tag);
  }

  getDifficultyLabel(difficulty: string): string {
    if (difficulty.toLowerCase() === 'medium') {
      return 'Med';
    }
    return difficulty;
  }

  toggleTagsPopover(): void {
    this.showTagsPopover = !this.showTagsPopover;
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    const tagsSection = target.closest('.tags-section');

    if (!tagsSection && this.showTagsPopover) {
      this.showTagsPopover = false;
    }
  }
}

<div class="sidebar-container">
  <!-- Search Header -->
  <div class="sidebar-header">
    <div class="search-wrapper">
      <svg class="search-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="11" cy="11" r="8"></circle>
        <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
      </svg>
      <input 
        type="text" 
        [(ngModel)]="searchQuery" 
        (ngModelChange)="filterQuestions()"
        placeholder="Search questions..."
        class="search-input"
      >
    </div>

    <!-- Filters -->
    <div class="filters-scroll">
      <div class="filters-group">
        <button 
          class="filter-chip easy" 
          [class.active]="selectedDifficulty === 'Easy'"
          (click)="toggleDifficulty('Easy')">
          Easy
        </button>
        <button 
          class="filter-chip medium" 
          [class.active]="selectedDifficulty === 'Medium'"
          (click)="toggleDifficulty('Medium')">
          Med
        </button>
        <button 
          class="filter-chip hard" 
          [class.active]="selectedDifficulty === 'Hard'"
          (click)="toggleDifficulty('Hard')">
          Hard
        </button>
        <div class="divider"></div>
        <button 
          class="filter-chip status" 
          [class.active]="showCompleted === true"
          (click)="toggleStatus(true)">
          Done
        </button>
      </div>
    </div>

    <!-- Tag Filter Section -->
    <div class="tags-section">
      <div class="tags-header">
        <span class="tags-label">Tags</span>
        <span class="tags-count" *ngIf="selectedTags.size > 0">({{ selectedTags.size }})</span>
      </div>
      <div class="tags-scroll">
        <div class="tags-group">
          <button
            *ngFor="let tag of availableTags"
            class="tag-chip"
            [class.active]="isTagSelected(tag)"
            [style.--tag-color]="getTagColor(tag)"
            (click)="toggleTag(tag)">
            {{ tag }}
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Question List -->
  <div class="questions-list">
    <div 
      *ngFor="let question of filteredQuestions" 
      class="question-item"
      [class.active]="question.filename === currentQuestionFilename"
      (click)="onSelect(question.filename)">
      
      <div class="question-status">
        <div class="status-indicator" [class.completed]="isQuestionCompleted(question.filename)">
          <svg *ngIf="isQuestionCompleted(question.filename)" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3">
            <polyline points="20 6 9 17 4 12"></polyline>
          </svg>
        </div>
      </div>

      <div class="question-content">
        <div class="question-title-row">
          <div class="question-title">{{ question.title }}</div>
          <div class="difficulty-badge" [ngClass]="'difficulty-' + question.difficulty.toLowerCase()">
            {{ getDifficultyLabel(question.difficulty) }}
          </div>
        </div>
        <div class="question-meta">
          <div class="question-tags">
            <span
              *ngFor="let tag of question.tags.slice(0, 2)"
              class="question-tag"
              [style.background-color]="getTagColor(tag) + '15'"
              [style.color]="getTagColor(tag)">
              {{ tag }}
            </span>
            <span *ngIf="question.tags.length > 2" class="tag-more">+{{ question.tags.length - 2 }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Empty State -->
    <div *ngIf="filteredQuestions.length === 0" class="empty-state">
      <p>No questions found</p>
    </div>
  </div>
</div>
